kind: Pod
apiVersion: v1
metadata:
  name: secret-environment
spec:
  containers:
    - name: cm-pod-cont
      image: nginx
      env:
        - name: db-username
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: db-password
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
      ports:
        - containerPort: 80
